version: '3.7'

name: lafs-web-stack

services:
  web:
    container_name: lafs-web
    image: lafs-web:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      API_HOST: "http://127.0.0.1"
      API_PORT: 3000
      API_USER: ""
      API_PASSWORD: ""
      API_PATH: "/api"
    ports:
      - 4200:4200

networks:
  default:
    external:
      name: lafs-net
